spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true