spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm
      username: root
      password: root
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.springboot.mybatis.plus
  global-config:
    id-type: 0
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: true
    capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
